services:
  sarrailantoine-app:
    image: dunglas/frankenphp:php8.2
    container_name: sarrailantoine-app
    restart: always
    networks:
      - backend
    depends_on:
      - sarrailantoine-db
    environment:
      SERVER_NAME: ${BLOG_DOMAIN}
      DB_DRIVER: mysql
      DB_HOST: sarrailantoine-db
      DB_PORT: 3306
      DB_NAME: ${BLOG_DB_NAME}
      DB_USER: ${BLOG_DB_USER}
      DB_PASS: ${BLOG_DB_PASS}
    volumes:
      - ./backend:/app
    ports:
      - "8088:80"

  sarrailantoine-db:
    image: mariadb:11
    container_name: sarrailantoine-db
    restart: always
    networks:
      - backend
    environment:
      MARIADB_DATABASE: ${BLOG_DB_NAME}
      MARIADB_USER: ${BLOG_DB_USER}
      MARIADB_PASSWORD: ${BLOG_DB_PASS}
      MARIADB_ROOT_PASSWORD: ${BLOG_DB_ROOT_PASS}
    volumes:
      - sarrailantoine_db_data:/var/lib/mysql

networks:
  backend:
    external: true

volumes:
  sarrailantoine_db_data:
